language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
script: script/cibuild
sudo: false
cache: bundler
notifications:
  email: false

matrix:
  include:
    -
      rvm: 1.9
      env: JEKYLL_VERSION=2.0
  fast_finish: true
env:
  - ""
  - JEKYLL_VERSION=3.0
  - JEKYLL_VERSION=2.0
